feat: add qrcode login
messense/aliyundrive-webdav pull request #444
Opened 2022-05-30 14:52 UTC by gngpp

作者能把这个pr合并下吗，加了QRCode终端扫码登陆，抓出来的refresh token经过测试是可以用的

2022-05-30 14:53 UTC, gngpp commented
测试在这里：https://github.com/gngpp/aliyundrive-webdav/blob/f378815061d1f010b68c7e169afd93d283532549/src/login/mod.rs#L158

2022-05-31 01:39 UTC, messense requested changes

2022-05-31 01:39 UTC, messense commented on Cargo.lock
> + "base64",
忘了提交 `Cargo.toml` 文件？

2022-05-31 01:39 UTC, messense commented on src/login/mod.rs
> +            std::thread::sleep(std::time::Duration::from_secs(2))
async 函数里面不应该用同步的 sleep ，应该用 tokio 中对应的异步的函数

2022-05-31 01:39 UTC, messense commented on src/login/model.rs
> +impl Into<QueryQrCodeCkForm> for GeneratorQrCodeResult {
一般实现 `From` 而不是 `Into`

2022-05-31 01:39 UTC, messense commented on src/login/mod.rs
> +}
可以直接 derive `PartialEq`、`Eq`，实现 `fmt::Display` 而不是 `ToString`，另外实现 `FromStr` 和 serde 的 Deserialize 来实现反序列化: https://github.com/serde-rs/serde/issues/908#issuecomment-298027413

2022-05-31 01:39 UTC, messense commented on src/login/model.rs
> +impl QrCodeScannerState for QueryQrCodeResult {
这个 `QrCodeScannerState` trait 只用了一次，没必要，直接写成普通的方法就行了。

2022-05-31 01:58 UTC, gngpp commented on src/login/model.rs
> +impl QrCodeScannerState for QueryQrCodeResult {
好，我先撤销提交吧，先全部重新改下

2022-05-31 01:58 UTC, closed without merging